server:
  domain: user
  version: 1.0
  jwtSecret: FanOne
  grpcAddress: "127.0.0.1:1001"

mysql:
  driverName: mysql
  host: 127.0.0.1
  poat: 3306
  database: grpc_todolist_tmp
  username: root
  password: root
  charset: utf8

etcd:
  address: 127.0.0.1:2379

redis:
  address: 127.0.0.1:6379
